import type { Landmark } from "@/src/types/pose";
import { angleBetween, scoreForRange } from "./vector";
export { angleBetween };
export const kneeAngle = (hip: Landmark, knee: Landmark, ankle: Landmark): number => angleBetween(hip, knee, ankle);
export const elbowAngle = (shoulder: Landmark, elbow: Landmark, wrist: Landmark): number => angleBetween(shoulder, elbow, wrist);
export const hipAngle = (shoulder: Landmark, hip: Landmark, knee: Landmark): number => angleBetween(shoulder, hip, knee);
export const normalizedAngle = (angle: number): number => Math.max(0, Math.min(180, angle));
export const angleScore = (angle: number, min: number, max: number, tolerance = 25): number => scoreForRange(normalizedAngle(angle), min, max, tolerance);
export const averageAngle = (angles: number[]): number => angles.length ? angles.reduce((sum, value) => sum + value, 0) / angles.length : 0;
export const symmetryScore = (left: number, right: number, tolerance = 25): number => scoreForRange(Math.abs(left - right), 0, tolerance, tolerance);
export const verticalAngle = (top: Landmark, bottom: Landmark): number => Math.atan2(bottom.x - top.x, bottom.y - top.y) * 180 / Math.PI;
export const angleDelta = (current: number, previous: number): number => current - previous;
export const isWithinAngle = (angle: number, min: number, max: number): boolean => angle >= min && angle <= max;
export const formScore = (scores: number[]): number => Math.round(scores.reduce((sum, score) => sum + score, 0) / Math.max(1, scores.length));
export const roundedAngle = (angle: number): number => Math.round(angle);
export const angleLabel = (angle: number): string => `${roundedAngle(angle)}°`;
export const angleError = (angle: number, target: number): number => Math.abs(angle - target);
export const hingeScore = (angle: number): number => angleScore(angle, 70, 115, 30);
export const straightLineScore = (angle: number): number => angleScore(angle, 165, 180, 20);
export const deepBendScore = (angle: number): number => angleScore(angle, 70, 110, 25);
export const controlledBendScore = (angle: number): number => angleScore(angle, 45, 125, 35);
export const uprightScore = (angle: number): number => angleScore(angle, 160, 180, 20);
export const angleRange = (angles: number[]): { min: number; max: number } => ({ min: Math.min(...angles, 0), max: Math.max(...angles, 0) });
export const angleVariance = (angles: number[]): number => { const mean = averageAngle(angles); return averageAngle(angles.map((angle) => (angle - mean) ** 2)); };
export const stableAngle = (angles: number[], tolerance = 8): boolean => { const range = angleRange(angles); return range.max - range.min <= tolerance; };
export const average = averageAngle;
