import type { Landmark } from "@/src/types/pose";

export type Vector3 = { x: number; y: number; z: number };
export const vectorBetween = (from: Landmark, to: Landmark): Vector3 => ({ x: to.x - from.x, y: to.y - from.y, z: to.z - from.z });
export const magnitude = (v: Vector3): number => Math.hypot(v.x, v.y, v.z);
export const dot = (a: Vector3, b: Vector3): number => a.x * b.x + a.y * b.y + a.z * b.z;
export const normalize = (v: Vector3): Vector3 => { const m = magnitude(v); return m ? { x: v.x / m, y: v.y / m, z: v.z / m } : { x: 0, y: 0, z: 0 }; };
export const distance = (a: Landmark, b: Landmark): number => magnitude(vectorBetween(a, b));
export const distance2D = (a: Landmark, b: Landmark): number => Math.hypot(a.x - b.x, a.y - b.y);
export const midpoint = (a: Landmark, b: Landmark): Landmark => ({ x: (a.x + b.x) / 2, y: (a.y + b.y) / 2, z: (a.z + b.z) / 2, visibility: Math.min(a.visibility, b.visibility) });
export const average = (values: number[]): number => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;
export const safeRatio = (a: number, b: number): number => b === 0 ? 0 : a / b;
export const clamp01 = (value: number): number => Math.max(0, Math.min(1, value));
export const lerp = (a: number, b: number, t: number): number => a + (b - a) * clamp01(t);
export const angleBetween = (a: Landmark, b: Landmark, c: Landmark): number => { const first = normalize(vectorBetween(b, a)); const second = normalize(vectorBetween(b, c)); return Math.acos(Math.max(-1, Math.min(1, dot(first, second)))) * 180 / Math.PI; };
export const scoreFromError = (error: number, tolerance: number): number => Math.max(0, Math.min(100, 100 - Math.abs(error) / Math.max(tolerance, 0.001) * 100));
export const scoreForRange = (value: number, min: number, max: number, tolerance: number): number => value >= min && value <= max ? 100 : scoreFromError(value < min ? value - min : value - max, tolerance);
export const averagePoint = (points: Landmark[]): Landmark => ({ x: average(points.map((p) => p.x)), y: average(points.map((p) => p.y)), z: average(points.map((p) => p.z)), visibility: average(points.map((p) => p.visibility)) });
export const smooth = (previous: number, next: number, alpha = 0.35): number => previous + (next - previous) * alpha;
export const range = (values: number[]): number => values.length ? Math.max(...values) - Math.min(...values) : 0;
export const median = (values: number[]): number => { const sorted = [...values].sort((a, b) => a - b); if (!sorted.length) return 0; const middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2; };
export const bodyLineDeviation = (shoulder: Landmark, hip: Landmark, ankle: Landmark): number => Math.abs((hip.x - shoulder.x) - (ankle.x - hip.x));
export const toScreenPoint = (point: Landmark, width: number, height: number, mirror = false) => ({ x: (mirror ? 1 - point.x : point.x) * width, y: point.y * height });
export const isInsideFrame = (point: Landmark, margin = 0.05): boolean => point.x >= margin && point.x <= 1 - margin && point.y >= margin && point.y <= 1 - margin;
export const confidenceScore = (points: Landmark[]): number => Math.round(average(points.map((p) => p.visibility)) * 100);
export const round = (value: number, decimals = 1): number => { const factor = 10 ** decimals; return Math.round(value * factor) / factor; };
export const clampScore = (value: number): number => Math.round(Math.max(0, Math.min(100, value)));
export const orientation = (a: Landmark, b: Landmark, c: Landmark): number => Math.sign((b.x - a.x) * (c.y - a.y) - (b.y - a.y) * (c.x - a.x));
export const mirror = (point: Landmark): Landmark => ({ ...point, x: 1 - point.x });
export const pointsVisible = (points: Landmark[], threshold = 0.55): boolean => points.every((point) => point.visibility >= threshold);
export const pointFinite = (point: Landmark): boolean => [point.x, point.y, point.z, point.visibility].every(Number.isFinite);
export const scoreTone = (score: number): "positive" | "neutral" | "warning" => score >= 80 ? "positive" : score >= 60 ? "neutral" : "warning";
