import type { ExerciseAnalysis, PoseFrame } from "@/src/types/pose";
import { landmark } from "@/src/types/pose";
import { angleScore, elbowAngle, hipAngle, kneeAngle, formScore } from "../geometry/angle";
import { scoreTone } from "../geometry/vector";
const point = (frame: PoseFrame, name: Parameters<typeof landmark>[1]) => landmark(frame, name)!;
const result = (score: number, feedback: string, metrics: Record<string, number>): ExerciseAnalysis => ({ phase: "ready", repCompleted: false, score: Math.round(score), feedback, tone: scoreTone(score), metrics });
export function squat(frame: PoseFrame): ExerciseAnalysis { const left = kneeAngle(point(frame, "leftHip"), point(frame, "leftKnee"), point(frame, "leftAnkle")); const right = kneeAngle(point(frame, "rightHip"), point(frame, "rightKnee"), point(frame, "rightAnkle")); const knee = (left + right) / 2; const top = knee > 155; const bottom = knee < 112; const score = formScore([angleScore(knee, 70, 115, 40), angleScore(Math.abs(left - right), 0, 22, 30)]); return result(score, score < 70 ? "Keep your knees tracking over your toes" : bottom ? "Nice depth — drive through your feet" : "Keep your chest proud", { kneeAngle: knee, isAtTop: top ? 1 : 0, isAtBottom: bottom ? 1 : 0 }); }
export function pushup(frame: PoseFrame): ExerciseAnalysis { const left = elbowAngle(point(frame, "leftShoulder"), point(frame, "leftElbow"), point(frame, "leftWrist")); const right = elbowAngle(point(frame, "rightShoulder"), point(frame, "rightElbow"), point(frame, "rightWrist")); const shoulder = point(frame, "leftShoulder"); const hip = point(frame, "leftHip"); const ankle = point(frame, "leftAnkle"); const line = Math.abs((hip.x - shoulder.x) - (ankle.x - hip.x)); const elbow = (left + right) / 2; const top = elbow > 155; const bottom = elbow < 95; const score = formScore([angleScore(elbow, 70, 110, 40), Math.max(0, 100 - line * 500)]); return result(score, score < 70 ? "Keep your body in one line" : bottom ? "Strong bottom position" : "Press the floor away", { elbowAngle: elbow, bodyLineError: line, isAtTop: top ? 1 : 0, isAtBottom: bottom ? 1 : 0 }); }
export function bicepCurl(frame: PoseFrame): ExerciseAnalysis { const left = elbowAngle(point(frame, "leftShoulder"), point(frame, "leftElbow"), point(frame, "leftWrist")); const right = elbowAngle(point(frame, "rightShoulder"), point(frame, "rightElbow"), point(frame, "rightWrist")); const elbow = (left + right) / 2; const top = elbow < 55; const bottom = elbow > 145; const score = formScore([angleScore(elbow, 35, 70, 30), angleScore(Math.abs(left - right), 0, 25, 35)]); return result(score, score < 70 ? "Keep elbows close to your ribs" : top ? "Squeeze at the top" : "Control the way down", { elbowAngle: elbow, isAtTop: top ? 1 : 0, isAtBottom: bottom ? 1 : 0 }); }
export function lunge(frame: PoseFrame): ExerciseAnalysis { const left = kneeAngle(point(frame, "leftHip"), point(frame, "leftKnee"), point(frame, "leftAnkle")); const right = kneeAngle(point(frame, "rightHip"), point(frame, "rightKnee"), point(frame, "rightAnkle")); const knee = Math.min(left, right); const top = left > 155 && right > 155; const bottom = knee < 105; const score = formScore([angleScore(knee, 75, 115, 40), angleScore(Math.abs(left - right), 0, 35, 45)]); return result(score, score < 70 ? "Keep your front knee stacked over your ankle" : bottom ? "Stable at the bottom" : "Drive through your front foot", { kneeAngle: knee, isAtTop: top ? 1 : 0, isAtBottom: bottom ? 1 : 0 }); }
