import { ScrollView, Text, View, StyleSheet, Pressable } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { Button } from "@/src/components/common/Button";
import { CameraSetupGuide } from "@/src/components/camera/CameraSetupGuide";
import { Colors } from "@/src/constants/Colors";
import { displayExercise, parseExercise, parseMode, type ExerciseId } from "@/src/types/pose";
export default function CameraSetupScreen() { const router = useRouter(); const params = useLocalSearchParams<{ exerciseId?: string; mode?: string }>(); const exerciseId = parseExercise(params.exerciseId) as ExerciseId; const mode = parseMode(params.mode); const start = (nextMode: "camera" | "demo") => router.replace({ pathname: "/live-workout", params: { exerciseId, mode: nextMode } } as never); return <ScreenContainer style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={Colors.foreground} /><Text style={styles.backText}>Choose another</Text></Pressable><Text style={styles.eyebrow}>GET READY</Text><Text style={styles.title}>{displayExercise(exerciseId)} setup</Text><Text style={styles.subtitle}>A few details make the feedback more reliable.</Text><CameraSetupGuide exerciseId={exerciseId} mode={mode} /><View style={styles.preview}><View style={styles.previewFrame}><MaterialIcons name={mode === "demo" ? "offline-bolt" : "videocam"} size={34} color={Colors.accent} /><Text style={styles.previewTitle}>{mode === "demo" ? "Deterministic stream ready" : "Live camera is optional"}</Text><Text style={styles.previewBody}>{mode === "demo" ? "The full pipeline runs without an active camera feed." : "Grant camera access in the next step when using a development build."}</Text></View></View><Button label={mode === "demo" ? "Start Demo Mode" : "Use live camera"} onPress={() => start(mode)} /><Pressable onPress={() => start(mode === "demo" ? "camera" : "demo")} style={styles.switch}><Text style={styles.switchText}>Switch to {mode === "demo" ? "live camera" : "Demo Mode"}</Text></Pressable></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ screen: { backgroundColor: Colors.background }, content: { padding: 22, gap: 15, paddingBottom: 35 }, back: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 15 }, backText: { color: Colors.foreground, fontWeight: "800" }, eyebrow: { color: Colors.accent, fontSize: 10, fontWeight: "900", letterSpacing: 1.4 }, title: { color: Colors.foreground, fontSize: 34, fontWeight: "900" }, subtitle: { color: Colors.muted, fontSize: 15 }, preview: { height: 230, borderRadius: 24, overflow: "hidden", backgroundColor: Colors.surfaceRaised, borderWidth: 1, borderColor: Colors.border }, previewFrame: { flex: 1, alignItems: "center", justifyContent: "center", padding: 28, gap: 10 }, previewTitle: { color: Colors.foreground, fontSize: 18, fontWeight: "900", textAlign: "center" }, previewBody: { color: Colors.muted, fontSize: 13, textAlign: "center", lineHeight: 19 }, switch: { alignItems: "center", paddingVertical: 8 }, switchText: { color: Colors.accent, fontWeight: "800" } });
