import { ScrollView, Text, View, StyleSheet, Pressable } from "react-native";
import { useRouter } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { Card } from "@/src/components/common/Card";
import { Button } from "@/src/components/common/Button";
import { Colors } from "@/src/constants/Colors";
import { EXERCISES } from "@/src/constants/Exercises";
import type { ExerciseId } from "@/src/types/pose";
export default function WorkoutSelectionScreen() { const router = useRouter(); const start = (id: ExerciseId, mode: "demo" | "camera") => router.push({ pathname: "/camera-setup", params: { exerciseId: id, mode } } as never); return <ScreenContainer style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={Colors.foreground} /><Text style={styles.backText}>Back</Text></Pressable><Text style={styles.eyebrow}>YOUR NEXT SESSION</Text><Text style={styles.title}>Choose your focus.</Text><Text style={styles.subtitle}>Every exercise uses the same explainable pose pipeline.</Text><View style={styles.list}>{EXERCISES.map((exercise) => <Card key={exercise.id} style={styles.exercise}><View style={[styles.icon, { backgroundColor: `${exercise.id === "squat" ? Colors.accent : exercise.id === "pushup" ? Colors.cyan : exercise.id === "bicep-curl" ? Colors.orange : Colors.lilac}22` }]}><MaterialIcons name={exercise.id === "squat" ? "fitness-center" : exercise.id === "pushup" ? "self-improvement" : exercise.id === "bicep-curl" ? "sports-handball" : "directions-run"} size={25} color={exercise.id === "squat" ? Colors.accent : exercise.id === "pushup" ? Colors.cyan : exercise.id === "bicep-curl" ? Colors.orange : Colors.lilac} /></View><View style={styles.exerciseCopy}><Text style={styles.exerciseName}>{exercise.name}</Text><Text style={styles.exerciseDescription}>{exercise.description} · {exercise.targetReps} target reps</Text><View style={styles.actions}><Button label="Demo" variant="secondary" onPress={() => start(exercise.id, "demo")} /><Button label="Camera" variant="ghost" onPress={() => start(exercise.id, "camera")} /></View></View></Card>)}</View><Text style={styles.privacy}>Private by default · camera frames never upload</Text></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ screen: { backgroundColor: Colors.background }, content: { padding: 22, gap: 14, paddingBottom: 40 }, back: { flexDirection: "row", gap: 8, alignItems: "center", marginBottom: 15 }, backText: { color: Colors.foreground, fontWeight: "800" }, eyebrow: { color: Colors.accent, fontSize: 10, fontWeight: "900", letterSpacing: 1.5 }, title: { color: Colors.foreground, fontSize: 34, fontWeight: "900", letterSpacing: -0.5 }, subtitle: { color: Colors.muted, fontSize: 15, lineHeight: 22, marginBottom: 10 }, list: { gap: 12 }, exercise: { flexDirection: "row", gap: 14 }, icon: { width: 50, height: 50, borderRadius: 17, alignItems: "center", justifyContent: "center" }, exerciseCopy: { flex: 1, gap: 4 }, exerciseName: { color: Colors.foreground, fontSize: 18, fontWeight: "900" }, exerciseDescription: { color: Colors.muted, fontSize: 12 }, actions: { flexDirection: "row", gap: 6, marginTop: 9 }, privacy: { color: Colors.muted, fontSize: 12, textAlign: "center", marginTop: 10 } });
