import { useMemo } from "react";
import { ScrollView, Text, View, StyleSheet, Pressable } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { Button } from "@/src/components/common/Button";
import { Card } from "@/src/components/common/Card";
import { MetricBadge } from "@/src/components/common/MetricBadge";
import { Colors } from "@/src/constants/Colors";
import { displayExercise, parseExercise, parseMode } from "@/src/types/pose";
export default function WorkoutSummaryScreen() { const router = useRouter(); const params = useLocalSearchParams<{ exerciseId?: string; mode?: string; reps?: string; score?: string; elapsed?: string; highlights?: string }>(); const exerciseId = parseExercise(params.exerciseId); const reps = Number(params.reps ?? 0); const score = Number(params.score ?? 0); const elapsed = Number(params.elapsed ?? 0); const highlights = useMemo(() => { try { return JSON.parse(params.highlights ?? "[]") as string[]; } catch { return []; } }, [params.highlights]); const source = parseMode(params.mode); return <ScreenContainer style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.replace("/" as never)} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={Colors.foreground} /><Text style={styles.backText}>Back to home</Text></Pressable><View style={styles.hero}><View style={styles.check}><MaterialIcons name="check" size={25} color={Colors.background} /></View><Text style={styles.eyebrow}>SESSION COMPLETE</Text><Text style={styles.title}>That’s a wrap.</Text><Text style={styles.subtitle}>{displayExercise(exerciseId)} · {source === "demo" ? "Demo Mode" : "Camera Mode"}</Text></View><Card style={styles.scoreCard}><Text style={styles.cardKicker}>FORM SCORE</Text><Text style={styles.bigScore}>{score ? `${score}%` : "—"}</Text><Text style={styles.scoreCopy}>{score >= 80 ? "Strong control across your reps." : score >= 60 ? "A solid start — keep refining your range." : "Shorten the range and focus on alignment."}</Text><View style={styles.metrics}><MetricBadge label="REPS" value={`${reps}`} /><MetricBadge label="TIME" value={`${Math.floor(elapsed / 60)}:${String(elapsed % 60).padStart(2, "0")}`} accent={Colors.cyan} /><MetricBadge label="MODE" value={source === "demo" ? "Demo" : "Live"} accent={Colors.lilac} /></View></Card><Card style={styles.coach}><View style={styles.coachHeader}><MaterialIcons name="auto-awesome" size={18} color={Colors.accent} /><Text style={styles.cardKicker}>COACH NOTE</Text></View>{(highlights.length ? highlights : ["Keep showing up — consistency beats perfection."]).slice(0, 3).map((item) => <View style={styles.note} key={item}><View style={styles.noteDot} /><Text style={styles.noteText}>{item}</Text></View>)}</Card><Button label="Save to history" onPress={() => router.replace("/" as never)} /><Pressable onPress={() => router.replace({ pathname: "/workout-selection" } as never)} style={styles.again}><Text style={styles.againText}>Train again</Text></Pressable><Text style={styles.privacy}>Saved locally · no camera frames uploaded</Text></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ screen: { backgroundColor: Colors.background }, content: { padding: 22, gap: 15, paddingBottom: 35 }, back: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 14 }, backText: { color: Colors.foreground, fontWeight: "800" }, hero: { alignItems: "center", gap: 8, paddingVertical: 8 }, check: { width: 54, height: 54, borderRadius: 27, backgroundColor: Colors.accent, alignItems: "center", justifyContent: "center", marginBottom: 8 }, eyebrow: { color: Colors.accent, fontSize: 10, fontWeight: "900", letterSpacing: 1.5 }, title: { color: Colors.foreground, fontSize: 36, fontWeight: "900" }, subtitle: { color: Colors.muted, fontSize: 14 }, scoreCard: { alignItems: "center", gap: 5, paddingVertical: 24 }, cardKicker: { color: Colors.muted, fontSize: 10, fontWeight: "900", letterSpacing: 1.5 }, bigScore: { color: Colors.accent, fontSize: 58, fontWeight: "900", letterSpacing: -2 }, scoreCopy: { color: Colors.muted, fontSize: 13, textAlign: "center" }, metrics: { flexDirection: "row", width: "100%", justifyContent: "space-around", marginTop: 20 }, coach: { gap: 12 }, coachHeader: { flexDirection: "row", alignItems: "center", gap: 8 }, note: { flexDirection: "row", gap: 10, alignItems: "flex-start" }, noteDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: Colors.accent, marginTop: 6 }, noteText: { color: Colors.foreground, fontSize: 14, lineHeight: 20, flex: 1 }, again: { alignItems: "center", padding: 10 }, againText: { color: Colors.accent, fontWeight: "800" }, privacy: { color: Colors.muted, fontSize: 11, textAlign: "center" } });
