import { useMemo } from "react";
import { FlatList, Text, View, StyleSheet, Pressable } from "react-native";
import { useRouter } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { Card } from "@/src/components/common/Card";
import { Button } from "@/src/components/common/Button";
import { Colors } from "@/src/constants/Colors";
import { displayExercise, noSessionsBody, relativeDate, sortNewestFirst, workoutDescription } from "@/src/types/pose";
import { useWorkoutStore } from "@/src/store/useWorkoutStore";
export default function HistoryScreen() { const router = useRouter(); const workouts = useWorkoutStore((state) => state.workouts); const items = useMemo(() => sortNewestFirst(workouts), [workouts]); return <ScreenContainer style={styles.screen}><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><Text style={styles.eyebrow}>YOUR MOVEMENT STORY</Text><Text style={styles.title}>History.</Text><Text style={styles.subtitle}>{items.length ? `${items.length} sessions · stored locally` : "Every session, kept on your device."}</Text></View>} ListEmptyComponent={<Card style={styles.empty}><View style={styles.emptyIcon}><MaterialIcons name="show-chart" size={24} color={Colors.background} /></View><Text style={styles.emptyTitle}>No movement logged yet</Text><Text style={styles.emptyBody}>{noSessionsBody()}</Text><Button label="Start Demo Mode" onPress={() => router.push({ pathname: "/camera-setup", params: { exerciseId: "squat", mode: "demo" } } as never)} /></Card>} renderItem={({ item }) => <Card style={styles.row}><View style={styles.rowTop}><View style={styles.exerciseIcon}><MaterialIcons name="fitness-center" size={18} color={Colors.accent} /></View><View style={styles.rowCopy}><Text style={styles.exercise}>{displayExercise(item.exerciseId)}</Text><Text style={styles.description}>{workoutDescription(item)}</Text></View><Text style={styles.score}>{Math.round(item.averageFormScore)}%</Text></View><View style={styles.rowFooter}><Text style={styles.date}>{relativeDate(item.startedAt)} · {item.source === "demo" ? "Demo" : "Camera"}</Text><Text style={styles.reps}>{item.reps} reps</Text></View></Card>} /></ScreenContainer>; }
const styles = StyleSheet.create({ screen: { backgroundColor: Colors.background }, content: { padding: 22, gap: 12, paddingBottom: 30, flexGrow: 1 }, header: { gap: 6, marginBottom: 10, marginTop: 8 }, eyebrow: { color: Colors.accent, fontSize: 10, fontWeight: "900", letterSpacing: 1.5 }, title: { color: Colors.foreground, fontSize: 36, fontWeight: "900" }, subtitle: { color: Colors.muted, fontSize: 14 }, row: { gap: 14 }, rowTop: { flexDirection: "row", alignItems: "center", gap: 12 }, exerciseIcon: { width: 38, height: 38, borderRadius: 13, backgroundColor: "#B9F06B22", alignItems: "center", justifyContent: "center" }, rowCopy: { flex: 1, gap: 4 }, exercise: { color: Colors.foreground, fontSize: 16, fontWeight: "900" }, description: { color: Colors.muted, fontSize: 12 }, score: { color: Colors.accent, fontSize: 20, fontWeight: "900" }, rowFooter: { flexDirection: "row", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: Colors.border, paddingTop: 11 }, date: { color: Colors.muted, fontSize: 11 }, reps: { color: Colors.foreground, fontSize: 11, fontWeight: "800" }, empty: { gap: 10, alignItems: "center", marginTop: 40, padding: 24 }, emptyIcon: { width: 48, height: 48, borderRadius: 24, backgroundColor: Colors.accent, alignItems: "center", justifyContent: "center" }, emptyTitle: { color: Colors.foreground, fontSize: 20, fontWeight: "900" }, emptyBody: { color: Colors.muted, fontSize: 13, lineHeight: 19, textAlign: "center", marginBottom: 5 } });
