import { useEffect, useState } from "react";
import { ScrollView, Text, TextInput, View, StyleSheet } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { Card } from "@/src/components/common/Card";
import { Button } from "@/src/components/common/Button";
import { Colors } from "@/src/constants/Colors";
import { averageWorkoutScore, privacyCopy, summaryStats, versionLabel } from "@/src/types/pose";
import { useUserStore } from "@/src/store/useUserStore";
import { useWorkoutStore } from "@/src/store/useWorkoutStore";
export default function ProfileScreen() { const profile = useUserStore((state) => state.profile); const hydrate = useUserStore((state) => state.hydrate); const updateProfile = useUserStore((state) => state.updateProfile); const workouts = useWorkoutStore((state) => state.workouts); const [name, setName] = useState(profile.displayName); const [goal, setGoal] = useState(profile.goal); useEffect(() => { void hydrate(); }, [hydrate]); useEffect(() => { setName(profile.displayName); setGoal(profile.goal); }, [profile.displayName, profile.goal]); const stats = summaryStats(workouts); return <ScreenContainer style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>YOUR PROFILE</Text><Text style={styles.title}>Build a practice you can trust.</Text><Text style={styles.subtitle}>Small habits. Measurable progress.</Text><Card style={styles.profileCard}><View style={styles.avatar}><Text style={styles.avatarText}>{name.slice(0, 1).toUpperCase()}</Text></View><View style={styles.fields}><TextInput value={name} onChangeText={setName} placeholder="Display name" placeholderTextColor={Colors.muted} style={styles.input} /><TextInput value={goal} onChangeText={setGoal} placeholder="Current goal" placeholderTextColor={Colors.muted} style={styles.input} /></View><Button label="Save profile" onPress={() => void updateProfile({ displayName: name.trim() || "Alex", goal: goal.trim() || "Move with confidence" })} /></Card><Text style={styles.sectionTitle}>All-time movement</Text><View style={styles.stats}><Card style={styles.stat}><Text style={styles.statValue}>{stats.sessions}</Text><Text style={styles.statLabel}>Sessions</Text></Card><Card style={styles.stat}><Text style={styles.statValue}>{stats.reps}</Text><Text style={styles.statLabel}>Total reps</Text></Card><Card style={styles.stat}><Text style={styles.statValue}>{stats.minutes}</Text><Text style={styles.statLabel}>Active min</Text></Card></View><Card style={styles.privacy}><Text style={styles.sectionTitle}>Your data, your rules.</Text><Text style={styles.privacyText}>{privacyCopy()}</Text><View style={styles.privacyRow}><Text style={styles.privacyLabel}>Offline-first storage</Text><Text style={styles.enabled}>Enabled</Text></View><View style={styles.privacyRow}><Text style={styles.privacyLabel}>Optional summary sync</Text><Text style={styles.optional}>Available</Text></View></Card><Text style={styles.footer}>{versionLabel()} · FitSense provides movement guidance, not medical advice.</Text></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ screen: { backgroundColor: Colors.background }, content: { padding: 22, gap: 15, paddingBottom: 35 }, eyebrow: { color: Colors.accent, fontSize: 10, fontWeight: "900", letterSpacing: 1.5, marginTop: 8 }, title: { color: Colors.foreground, fontSize: 32, fontWeight: "900", lineHeight: 37 }, subtitle: { color: Colors.muted, fontSize: 14 }, profileCard: { gap: 15, alignItems: "center", marginTop: 8 }, avatar: { width: 70, height: 70, borderRadius: 35, backgroundColor: Colors.accent, alignItems: "center", justifyContent: "center" }, avatarText: { color: Colors.background, fontSize: 30, fontWeight: "900" }, fields: { width: "100%", gap: 10 }, input: { color: Colors.foreground, backgroundColor: Colors.surfaceRaised, borderWidth: 1, borderColor: Colors.border, borderRadius: 15, paddingHorizontal: 14, minHeight: 48, fontSize: 14 }, sectionTitle: { color: Colors.foreground, fontSize: 17, fontWeight: "900" }, stats: { flexDirection: "row", gap: 9 }, stat: { flex: 1, alignItems: "center", padding: 14, gap: 5 }, statValue: { color: Colors.accent, fontSize: 24, fontWeight: "900" }, statLabel: { color: Colors.muted, fontSize: 10, fontWeight: "700" }, privacy: { gap: 12 }, privacyText: { color: Colors.muted, fontSize: 13, lineHeight: 20 }, privacyRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderTopWidth: 1, borderTopColor: Colors.border, paddingTop: 11 }, privacyLabel: { color: Colors.foreground, fontSize: 13, fontWeight: "700" }, enabled: { color: Colors.accent, fontWeight: "800", fontSize: 12 }, optional: { color: Colors.cyan, fontWeight: "800", fontSize: 12 }, footer: { color: Colors.muted, textAlign: "center", fontSize: 11, lineHeight: 17, marginTop: 5 } });
